backend:
  name: github
  repo: janprill/a-modo-nostro

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "soups"
    label: "Eintöpfe und Suppen"
    folder: "soups"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pizza"
    label: "Pizza"
    folder: "pizza"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pasta"
    label: "Pasta"
    folder: "pasta"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "salads"
    label: "Salads"
    folder: "salads"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "rustikal"
    label: "Rustikal"
    folder: "rustikal"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "kids"
    label: "Kids"
    folder: "kids"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}